; PlatformIO Project Configuration File

[platformio]
default_envs = esp32c3_rc522_espidf

[env]
platform = espressif32
board = esp32-c3-devkitm-1
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=5

; ESP32-C3 with RC522 using ESP-IDF
[env:esp32c3_rc522_espidf]
framework = espidf
extra_scripts = 
	pre:extra_script.py