---
config:
  layout: elk  
  look: classic
---
stateDiagram-v2
  direction TB
    [*] --> IDLE :esp_event
    
    state S1 <<choice>>
    IDLE --> S1:event received
    S1 --> BUILD_PAYLOAD : clock synced
    S1 --> BACKLOG: wait for NTP_SYNC
    BACKLOG --> S1 : retry event

    BUILD_PAYLOAD --> CALC_TIMESTAMP
    CALC_TIMESTAMP --> ADD_DEVICE_INFO : insert timestamp
    ADD_DEVICE_INFO --> ADD_HEALTH : insert device_id
 
    ADD_HEALTH --> PAYLOAD_READY : insert health_report  

    PAYLOAD_READY --> STORE_PAYLOAD : trigger FS
    PAYLOAD_READY --> SEND_PAYLOAD : trigger HTTP
    STORE_PAYLOAD --> [*]:esp_event_post
    SEND_PAYLOAD --> [*] :esp_event_post
    
    note left of CALC_TIMESTAMP
        real_timestamp = event_uptime + ntp_offset
    end note
    
    note left of ADD_DEVICE_INFO
        device_id = normalized MAC address (@boot-time)
    end note

    note left of ADD_HEALTH
        device_health_report from system_monitor (5min refresh)
    end note