---
config:
  layout: elk
---
stateDiagram-v2
  direction TB
  [*] --> IDLE : esp_event

  IDLE --> CHECK_WIFI: event received

  state S1 <<choice>>
  state S2 <<choice>>
  CHECK_WIFI --> S1
  S1 --> RETRIEVE_FROM_FS : Online
  S1 --> RETRY_LOGIC : Offline 

  RETRIEVE_FROM_FS --> SEND_HTTP : payload ready
  SEND_HTTP --> S2
  S2 --> CONFIRMED : HTTP 200
  S2 --> RETRY_LOGIC : HTTP fail

  RETRY_LOGIC --> RETRIEVE_FROM_FS : Retry (backoff)
  RETRY_LOGIC --> QUEUE_LOCAL : Max retries

  QUEUE_LOCAL --> BROADCAST_STATUS : Stored for later
  CONFIRMED --> BROADCAST_STATUS
  BROADCAST_STATUS --> [*]:esp_event_post

  note right of RETRY_LOGIC
    Exponential backoff: 1s, 2s, 4s, 8s, 16s
    Flag after max_reties: tryAgain_on_connection
  end note